# Generated by Django 5.0.6 on 2024-05-21 14:14

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_board', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=django_quill.fields.QuillField(help_text='Enter your text here', verbose_name='Text'),
        ),
    ]
