# Generated by Django 5.0.6 on 2024-05-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_board', '0003_alter_ad_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'permissions': [('view_unpublished_ad', 'Can view unpublished ads')], 'verbose_name': 'Ad', 'verbose_name_plural': 'Ads'},
        ),
    ]
