# Generated by Django 5.0.6 on 2024-06-28 04:37

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_board', '0004_alter_ad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='text_en',
            field=django_quill.fields.QuillField(help_text='Enter your text here', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='ad',
            name='text_ru',
            field=django_quill.fields.QuillField(help_text='Enter your text here', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_en',
            field=models.CharField(help_text='Enter your title here', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_ru',
            field=models.CharField(help_text='Enter your title here', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(help_text='Enter your category name here', max_length=255, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(help_text='Enter your category name here', max_length=255, null=True, unique=True, verbose_name='Category name'),
        ),
    ]
