# Generated by Django 5.0.6 on 2024-06-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_board', '0004_alter_ad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(help_text='Enter your category name here', max_length=255, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(help_text='Enter your category name here', max_length=255, null=True, unique=True, verbose_name='Category name'),
        ),
    ]
