# Generated by Django 5.0.6 on 2024-05-15 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Enter your email', max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, help_text='Enter your first name', max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, help_text='Enter your last name', max_length=255, null=True, verbose_name='Last name')),
                ('nickname', models.CharField(blank=True, help_text='Enter your nickname in the game', max_length=255, null=True, verbose_name='Nickname')),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='avatars', verbose_name='Avatar')),
                ('date_birth', models.DateField(blank=True, help_text='Enter your date of birth', null=True, verbose_name='Date of birth')),
                ('phone_number', models.CharField(blank=True, help_text='Enter your phone number', max_length=255, null=True, verbose_name='Phone number')),
                ('discord_url_profile', models.URLField(blank=True, help_text='Enter your Discord profile URL', max_length=255, null=True, verbose_name='Discord profile URL')),
                ('about_me', models.TextField(blank=True, help_text='Enter your about me here', null=True, verbose_name='About Me')),
                ('last_time_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
