# Generated by Django 5.0.6 on 2024-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(help_text='Enter your nickname in the game', max_length=255, verbose_name='Nickname'),
        ),
    ]
