# Generated by Django 5.0.6 on 2024-06-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_steam_url_profile_user_telegram_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reason_ban',
            field=models.TextField(blank=True, help_text='Enter the reason for the ban', null=True, verbose_name='Reason for ban'),
        ),
    ]
