# Generated by Django 5.0.6 on 2024-06-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_discord_url_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord_url_profile',
            field=models.CharField(blank=True, help_text='Enter your Discord nickname', max_length=255, null=True, verbose_name='Your Discord account'),
        ),
    ]
