# Generated by Django 5.0.6 on 2024-05-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your title here', max_length=255, verbose_name='Title')),
                ('text', models.TextField(help_text='Enter your text here', verbose_name='Text')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
    ]
