# Generated by Django 5.0.6 on 2024-06-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_newsletter_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_sent_email',
            field=models.BooleanField(default=False, verbose_name='Is sent'),
        ),
    ]
