# Generated by Django 5.0.6 on 2024-06-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_is_sent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='is_sent_email',
            field=models.BooleanField(default=False, help_text='Indicates whether the newsletter has been sent to users via email.', verbose_name='Email sent'),
        ),
    ]
