# Generated by Django 5.0.6 on 2024-06-28 04:57

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_alter_newsletter_is_sent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='text_en',
            field=django_quill.fields.QuillField(help_text='Enter your text here', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='text_ru',
            field=django_quill.fields.QuillField(help_text='Enter your text here', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='title_en',
            field=models.CharField(help_text='Enter your title here', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='title_ru',
            field=models.CharField(help_text='Enter your title here', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
