# Generated by Django 5.0.6 on 2024-05-15 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ad_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('DEC', 'Declined')], default='PEN', help_text='Shows the current status of this request', max_length=3, verbose_name='Status')),
                ('text', models.TextField(help_text='Enter your text here', verbose_name='Text')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='Date of change')),
                ('date_status_change', models.DateTimeField(blank=True, null=True, verbose_name='Date of status change')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_board.ad', verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
    ]
