# Generated by Django 5.0.6 on 2024-05-15 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('response_board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['author'], name='response_bo_author__3d6c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['ad'], name='response_bo_ad_id_bace63_idx'),
        ),
    ]
