# Generated by Django 5.0.6 on 2024-06-16 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_board', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='date_status_change',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 6, 16, 20, 22, 55, 189441, tzinfo=datetime.timezone.utc), verbose_name='Date of status change'),
            preserve_default=False,
        ),
    ]
