# Generated by Django 5.0.6 on 2024-06-28 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_board', '0004_alter_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='text_en',
            field=models.TextField(help_text='Enter your text here (1000 characters max)', null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='response',
            name='text_ru',
            field=models.TextField(help_text='Enter your text here (1000 characters max)', null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Text'),
        ),
    ]
